package su.nightexpress.nexshop.shop.virtual.editor;

public enum VirtualEditorType {

    CHANGE_TITLE,
    CHANGE_PAGES,
    CHANGE_ICON,
    CHANGE_DISCOUNTS,
    CHANGE_PRODUCTS,
    CHANGE_PERMISSION,
    CHANGE_TRANSACTIONS,
    CHANGE_CITIZENS_ID,
    CHANGE_VIEW_DESIGN,
    CREATE_SHOP,
    CREATE_DISCOUNT,

    DISCOUNT_CHANGE_DISCOUNT,
    DISCOUNT_CHANGE_DAY,
    DISCOUNT_CHANGE_TIME,

    PRODUCT_CHANGE_PREVIEW,
    PRODUCT_CHANGE_ITEM,
    PRODUCT_CHANGE_COMMANDS,
    PRODUCT_CHANGE_DISCOUNT,
    PRODUCT_CHANGE_ITEM_META,
    PRODUCT_CHANGE_CURRENCY,

    PRODUCT_CHANGE_PRICE_BUY,
    PRODUCT_CHANGE_PRICE_BUY_MIN,
    PRODUCT_CHANGE_PRICE_BUY_MAX,
    PRODUCT_CHANGE_PRICE_SELL,
    PRODUCT_CHANGE_PRICE_SELL_MIN,
    PRODUCT_CHANGE_PRICE_SELL_MAX,

    PRODUCT_CHANGE_LIMIT,
    PRODUCT_CHANGE_LIMIT_BUY_AMOUNT,
    PRODUCT_CHANGE_LIMIT_BUY_RESET,
    PRODUCT_CHANGE_LIMIT_SELL_AMOUNT,
    PRODUCT_CHANGE_LIMIT_SELL_RESET,

    PRODUCT_CHANGE_PRICE_RND,
    PRODUCT_CHANGE_PRICE_RND_TOGGLE,
    PRODUCT_CHANGE_PRICE_RND_TIME_DAY,
    PRODUCT_CHANGE_PRICE_RND_TIME_TIME,
}
